---
# Blastochor config
# Set data harvest parameters. See README.md for default values.

# Setup
api_key_env: TE-PAPA-KEY
mapping_file: gbifmap.yaml
corefile: core
input_dir: input_files
output_dir: output_files
use_skiplist: False
skipfile: null
min_image_size: 0
max_list_size: 100

# Run
mode: search
quiet: False
base_url: https://data.tepapa.govt.nz/collection
endpoint: object

# List mode settings
list_source: null

# Search mode settings
max_records: 50
size: 50

query: "*"
sort_field: null
sort_value: null

filter:
  collection: Plants
  allows_download: null
  keyword_fields: null
  keyword_values: null