---
# Blastochor config
# Set data harvest parameters. See README.md for default values.

# Setup
api_key_env: TE-PAPA-KEY
mapping_file: _work_maps/_work_agentsmap.yaml
input_dir: input_files
output_dir: output_files
use_skiplist: False
skipfile: null
min_image_size: 0
max_list_size: 100
clean_newlines: true
coordinate_workaround: false

# Group rows
group_rows: false
parent_label: null
parent_fields:
  include: null
  fields: null
child_fields:
  include: null
  fields: null
ungrouped_fields:
  include: null
  fields: null

# Sensitive data protection
restrict_locality: false

# Incorporate EMu data
emufile: collectionevents.xml

# Profiler
profiler_on: false
profiler_filename: null

# Run
mode: scroll
quiet: true
base_url: https://data.tepapa.govt.nz/collection
endpoint: agent
timeout: 5
attempts: 3

# List mode settings
list_source: null

# Search/scroll mode settings
max_records: -1
size: 1000

query: "*"
sort: -_meta.modified

filter:
  collection: null
  allows_download: null
  keyword_fields: type
  keyword_values: Person