---
# Blastochor default config
# Don't change these values too much! Make a new project instead.

# Setup
api_key_env: TE-PAPA-KEY
mapping_file: defaultmap.yaml
input_dir: input_files
output_dir: output_files
use_skiplist: False
skipfile: null
min_image_size: 0
max_list_size: 100
clean_newlines: true
coordinate_workaround: true

# Group rows
group_rows: false
parent_label: null
parent_fields:
  include: null
  fields: null
child_fields:
  include: null
  fields: null
ungrouped_fields:
  include: null
  fields: null

# Sensitive data protection
restrict_locality: true

# Incorporate EMu data
emufile: null

# Run
mode: search
quiet: true
base_url: https://data.tepapa.govt.nz/collection
endpoint: object
timeout: 5
attempts: 3

# List mode settings
list_source: null

# Search/scroll mode settings
record_limit: null
size: 100

query: "*"
sort: -id

filter:
  collection: null
  allows_download: null
  keyword_fields: null
  keyword_values: null