---
# Blastochor config for GBIF Plants collection dataset
# Don't change these values - create a new project instead

# Setup
api_key_env: TPAK-GBIF
mapping_file: gbif-plants.yaml
input_dir: input_files
output_dir: output_files
use_skiplist: False
skipfile: null
min_image_size: 0
max_list_size: 100
clean_newlines: true
coordinate_workaround: true

# Group rows
group_rows: false
parent_label: null
parent_fields:
  include: null
  fields: null
child_fields:
  include: null
  fields: null
ungrouped_fields:
  include: null
  fields: null

# Sensitive data protection
restrict_locality: true

# Incorporate EMu data
emufile: collectionevents.xml

# Run
mode: scroll
quiet: false
base_url: https://data.tepapa.govt.nz/collection
endpoint: object
timeout: 10
attempts: 3

# List mode settings
list_source: null

# Search/scroll mode settings
record_limit: null
size: 1000

query: "*"
sort: -_meta.modified

filter:
  collection: Plants
  allows_download: null
  keyword_fields: null
  keyword_values: null